### ISSUE TITLE
View wiki on macOS

### ISSUE THREAD

**Issue by henrikhelmers** [landakram/kiwi#1]
What is the best way to view Kiwi-generated content on OS X? I imagine you could run some kind of minimal web server in the Dropbox app directory, and I'm thinking you might have set up something like this for your own usage?

**Comment by landakram** [comment]
@henrikhelmers, the data format _should_ be compatible with [Commonplace](https://github.com/fredoliveira/commonplace) which you can try out. I haven't looked at compatibility with Commonplace in a while, so it may not work. Most definitely, the LaTeX rendering isn't supported in Commonplace, since I hacked that in. 

I'm also working on a web accessible version -- that's the way I view my wiki on OS X. I hope to have it pushed up soon, but in the meantime, try out commonplace and see if that works. I will say that I hope to change the data format in a coming release to be more flexible -- it's very difficult to extend at the moment. 

Hope that helps!
