### ISSUE TITLE
How much of what flavor of Markdown does Kiwi support?

### ISSUE THREAD

**Issue by FrankDMartinez** [landakram/kiwi#7]
For example, does it support "a href"s to be able to link to specific parts of specific files? Tagging of files?

**Comment by landakram** [comment]
Kiwi uses [hoedown](https://github.com/hoedown/hoedown) for markdown rendering. By default, these extensions are enabled: 

  * `hoedown.Extensions.TABLES`: Parse PHP-Markdown style tables.
  * `hoedown.Extensions.FENCED_CODE`: Parse fenced code blocks.
  * `hoedown.Extensions.FOOTNOTES`: Parse footnotes.
  * `hoedown.Extensions.AUTOLINK`: Automatically turn safe URLs into links.
  * `hoedown.Extensions.STRIKETHROUGH`: Parse `~~strikethrough~~` spans.
  * `hoedown.Extensions.UNDERLINE`: Parse `_underline_` instead of emphasis.
  * `hoedown.Extensions.HIGHLIGHT`: Parse `==highlight==` spans.
  * `hoedown.Extensions.QUOTE`: Render `\"quotes\"` as `<q>quotes</q>`.
  * `hoedown.Extensions.SUPERSCRIPT`: Parse `super^script`.
  * Rendering of `- [ ]` checkboxes. 
  * Rendering of wiki style `[[ ]]` links. 

Right now the wiki style links don't support linking to a specific part of a specific wiki page. 

Also, a quick test shows that you can link to another part of the same page using HTML `<a>` anchors, but it's kind of clunky as it opens in the built-in browser meant for external URLs. 

I'm not 100% sure what you mean by tagging files. Can you clarify that?

**Comment by FrankDMartinez** [comment]
In some products, such as the Bear app, files can be tagged with, say, #ABCDEFG, and One can then select all files with that particular tag to look at, similar to how Wikipedia has "Categories" at the end of many articles.

**Comment by landakram** [comment]
That would be awesome, but it's not implemented yet. 

As a workaround, I typically make pages named with the intended "category". These pages have a list of other wiki pages that belong in the category.

**Comment by landakram** [comment]
@FrankDMartinez, I opened a separate issue to track work on tags, which I think is a great idea: https://github.com/landakram/kiwi/issues/12

Closing this one.
